// Complete translations for all 9 languages
// Every UI string must be translated - no mixing of languages

export const languages = [
  { code: 'en', name: 'English', nativeName: 'English', dir: 'ltr' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', dir: 'ltr' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', dir: 'ltr' },
  { code: 'fr', name: 'French', nativeName: 'Français', dir: 'ltr' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', dir: 'ltr' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', dir: 'rtl' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', dir: 'ltr' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', dir: 'ltr' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', dir: 'ltr' },
];

const baseTranslations = {
  // Status Badges
  'status.verified': { en: 'Verified', hi: 'वेरिफाइड', es: 'Verificado', fr: 'Vérifié', de: 'Verifiziert', ar: 'موثّق', bn: 'যাচাইকৃত', ta: 'சரிபார்க்கப்பட்டது', te: 'ధృవీకరించబడింది' },
  'status.partial': { en: 'Partially Verified', hi: 'आंशिक रूप से सत्यापित', es: 'Parcialmente Verificado', fr: 'Partiellement Vérifié', de: 'Teilweise Verifiziert', ar: 'موثّق جزئياً', bn: 'আংশিকভাবে যাচাইকৃত', ta: 'பகுதியளவு சரிபார்க்கப்பட்டது', te: 'భాగంగా ధృవీకరించబడింది' },
  'status.false': { en: 'False', hi: 'गलत', es: 'Falso', fr: 'Faux', de: 'Falsch', ar: 'زائف', bn: 'ভুল', ta: 'தவறு', te: 'తప్పుడు' },
  // Navigation
  'nav.home': { en: 'Home', hi: 'होम', es: 'Inicio', fr: 'Accueil', de: 'Startseite', ar: 'الرئيسية', bn: 'হোম', ta: 'முகப்பு', te: 'హోమ్' },
  'nav.articles': { en: 'Articles', hi: 'लेख', es: 'Artículos', fr: 'Articles', de: 'Artikel', ar: 'المقالات', bn: 'নিবন্ধ', ta: 'கட்டுரைகள்', te: 'వ్యాసాలు' },
  'nav.leaderboard': { en: 'Leaderboard', hi: 'लीडरबोर्ड', es: 'Clasificación', fr: 'Classement', de: 'Bestenliste', ar: 'لوحة المتصدرين', bn: 'লিডারবোর্ড', ta: 'தலைவர் பலகை', te: 'లీడర్‌బోర్డ్' },
  'nav.badges': { en: 'Badges', hi: 'बैज', es: 'Insignias', fr: 'Badges', de: 'Abzeichen', ar: 'الشارات', bn: 'ব্যাজ', ta: 'பதக்கங்கள்', te: 'బ్యాడ్జ్‌లు' },
  'nav.outline': { en: 'Outline', hi: 'रूपरेखा', es: 'Esquema', fr: 'Aperçu', de: 'Überblick', ar: 'الخطوط العريضة', bn: 'রূপরেখা', ta: 'அவுட்லைன்', te: 'అవుట్‌లైన్' },

  // Header
  'header.login': { en: 'Log in', hi: 'लॉग इन', es: 'Iniciar sesión', fr: 'Se connecter', de: 'Anmelden', ar: 'تسجيل الدخول', bn: 'লগইন', ta: 'உள்நுழைக', te: 'లాగిన్' },

  // Hero Section
  'hero.badge': { en: 'AI-POWERED VERIFICATION', hi: 'एआई-संचालित सत्यापन', es: 'VERIFICACIÓN POTENCIADA POR IA', fr: 'VÉRIFICATION PAR IA', de: 'KI-GESTÜTZTE VERIFIZIERUNG', ar: 'التحقق المدعوم بالذكاء الاصطناعي', bn: 'এআই-চালিত যাচাইকরণ', ta: 'AI-இயங்கும் சரிபார்ப்பு', te: 'AI-శక్తితో ధృవీకరణ' },
  'hero.title': { en: 'VerityGuard', hi: 'VerityGuard', es: 'VerityGuard', fr: 'VerityGuard', de: 'VerityGuard', ar: 'VerityGuard', bn: 'VerityGuard', ta: 'VerityGuard', te: 'VerityGuard' },
  'hero.subtitle': { en: 'Truth in the Digital Age', hi: 'डिजिटल युग में सत्य', es: 'Verdad en la Era Digital', fr: 'La Vérité à l\'Ère Numérique', de: 'Wahrheit im digitalen Zeitalter', ar: 'الحقيقة في العصر الرقمي', bn: 'ডিজিটাল যুগে সত্য', ta: 'டிஜிட்டல் யுகத்தில் உண்மை', te: 'డిజిటల్ యుగంలో సత్యం' },
  'hero.description': { en: 'VerityGuard uses advanced machine learning to analyze news articles and provide real-time credibility scores. Join thousands of users fighting misinformation.', hi: 'VerityGuard उन्नत मशीन लर्निंग का उपयोग करके समाचार लेखों का विश्लेषण करता है और वास्तविक समय विश्वसनीयता स्कोर प्रदान करता है। गलत सूचना के खिलाफ लड़ाई में हजारों उपयोगकर्ताओं से जुड़ें।', es: 'VerityGuard utiliza aprendizaje automático avanzado para analizar artículos de noticias y proporcionar puntuaciones de credibilidad en tiempo real. Únete a miles de usuarios luchando contra la desinformación.', fr: 'VerityGuard utilise l\'apprentissage automatique avancé pour analyser les articles de presse et fournir des scores de crédibilité en temps réel. Rejoignez des milliers d\'utilisateurs luttant contre la désinformation.', de: 'VerityGuard verwendet fortschrittliches maschinelles Lernen, um Nachrichtenartikel zu analysieren und Echtzeit-Glaubwürdigkeitsbewertungen zu liefern. Schließen Sie sich Tausenden von Benutzern an, die gegen Fehlinformationen kämpfen.', ar: 'يستخدم VerityGuard التعلم الآلي المتقدم لتحليل المقالات الإخبارية وتوفير درجات المصداقية في الوقت الفعلي. انضم إلى آلاف المستخدمين الذين يحاربون المعلومات المضللة.', bn: 'VerityGuard উন্নত মেশিন লার্নিং ব্যবহার করে সংবাদ নিবন্ধ বিশ্লেষণ করে এবং রিয়েল-টাইম বিশ্বাসযোগ্যতা স্কোর প্রদান করে। ভুল তথ্যের বিরুদ্ধে লড়াইয়ে হাজার হাজার ব্যবহারকারীর সাথে যোগ দিন।', ta: 'VerityGuard மேம்பட்ட இயந்திர கற்றலைப் பயன்படுத்தி செய்தி கட்டுரைகளை பகுப்பாய்வு செய்து நிகழ் நேர நம்பகத்தன்மை மதிப்பெண்களை வழங்குகிறது. தவறான தகவலுக்கு எதிராக போராடும் ஆயிரக்கணக்கான பயனர்களுடன் சேரவும்.', te: 'VerityGuard అధునాతన మెషీన్ లెర్నింగ్‌ను ఉపయోగించి వార్తా కథనాలను విశ్లేషిస్తుంది మరియు నిజ-సమయ విశ్వసనీయత స్కోర్‌లను అందిస్తుంది. తప్పుడు సమాచారానికి వ్యతిరేకంగా పోరాడుతున్న వేలాది మంది వినియోగదారులతో చేరండి।' },
  'hero.getStarted': { en: 'Get Started', hi: 'शुरू करें', es: 'Comenzar', fr: 'Commencer', de: 'Loslegen', ar: 'ابدأ', bn: 'শুরু করুন', ta: 'தொடங்கவும்', te: 'ప్రారంభించండి' },
  'hero.learnMore': { en: 'Learn More', hi: 'और जानें', es: 'Saber Más', fr: 'En Savoir Plus', de: 'Mehr Erfahren', ar: 'اعرف المزيد', bn: 'আরও জানুন', ta: 'மேலும் அறிக', te: 'మరింత తెలుసుకోండి' },
  'hero.poweredBy': { en: 'POWERED BY', hi: 'द्वारा संचालित', es: 'IMPULSADO POR', fr: 'PROPULSÉ PAR', de: 'UNTERSTÜTZT VON', ar: 'مدعوم من', bn: 'দ্বারা চালিত', ta: 'இயக்குபவர்', te: 'ద్వారా అందించబడింది' },
  'hero.tech': { en: 'Advanced ML & NLP Technology', hi: 'एडवांस्ड एमएल और एनएलपी टेक्नोलॉजी', es: 'Tecnología Avanzada de ML y NLP', fr: 'Technologie ML et NLP Avancée', de: 'Fortgeschrittene ML- und NLP-Technologie', ar: 'تقنية ML و NLP المتقدمة', bn: 'উন্নত ML এবং NLP প্রযুক্তি', ta: 'மேம்பட்ட ML & NLP தொழில்நுட்பம்', te: 'అధునాతన ML & NLP సాంకేతికత' },

  // Hero Stats
  'hero.stats.articles': { en: 'Articles Verified', hi: 'सत्यापित लेख', es: 'Artículos Verificados', fr: 'Articles Vérifiés', de: 'Verifizierte Artikel', ar: 'المقالات المتحققة', bn: 'যাচাইকৃত নিবন্ধ', ta: 'சரிபார்க்கப்பட்ட கட்டுரைகள்', te: 'ధృవీకరించబడిన వ్యాసాలు' },
  'hero.stats.accuracy': { en: 'Accuracy Rate', hi: 'सटीकता दर', es: 'Tasa de Precisión', fr: 'Taux de Précision', de: 'Genauigkeitsrate', ar: 'معدل الدقة', bn: 'নির্ভুলতার হার', ta: 'துல்லிய விகிதம்', te: 'ఖచ్చితత్వ రేటు' },
  'hero.stats.languages': { en: 'Languages', hi: 'भाषाएँ', es: 'Idiomas', fr: 'Langues', de: 'Sprachen', ar: 'اللغات', bn: 'ভাষা', ta: 'மொழிகள்', te: 'భాషలు' },
  'hero.stats.users': { en: 'Active Users', hi: 'सक्रिय उपयोगकर्ता', es: 'Usuarios Activos', fr: 'Utilisateurs Actifs', de: 'Aktive Benutzer', ar: 'المستخدمون النشطون', bn: 'সক্রিয় ব্যবহারকারী', ta: 'செயலில் உள்ள பயனர்கள்', te: 'క్రియాశీల వినియోగదారులు' },

  // Articles
  'articles.title': { en: 'Latest Articles', hi: 'ताज़ा लेख', es: 'Últimos Artículos', fr: 'Derniers Articles', de: 'Neueste Artikel', ar: 'أحدث المقالات', bn: 'সর্বশেষ নিবন্ধ', ta: 'சமீபத்திய கட்டுரைகள்', te: 'తాజా వ్యాసాలు' },
  'articles.filters': { en: 'Filters', hi: 'फ़िल्टर्स', es: 'Filtros', fr: 'Filtres', de: 'Filter', ar: 'الفلاتر', bn: 'ফিল্টার', ta: 'வடிப்பான்கள்', te: 'ఫిల్టర్‌లు' },
  'articles.loginPrompt': { en: 'Login to see location-based news', hi: 'स्थान-आधारित समाचार देखने के लिए लॉगिन करें', es: 'Inicia sesión para ver noticias locales', fr: 'Connectez-vous pour voir les actualités locales', de: 'Melden Sie sich an, um standortbasierte Nachrichten zu sehen', ar: 'سجل الدخول لرؤية الأخبار المحلية', bn: 'স্থান-ভিত্তিক সংবাদ দেখতে লগইন করুন', ta: 'இடம் சார்ந்த செய்திகளைக் காண உள்நுழையவும்', te: 'స్థాన-ఆధారిత వార్తలను చూడటానికి లాగిన్ చేయండి' },
  'articles.setLocationPrompt': { en: 'Set your location to see local news', hi: 'स्थानीय समाचार देखने के लिए अपना स्थान सेट करें', es: 'Establece tu ubicación para ver noticias locales', fr: 'Définissez votre emplacement pour voir les actualités locales', de: 'Legen Sie Ihren Standort fest, um lokale Nachrichten zu sehen', ar: 'حدد موقعك لرؤية الأخبار المحلية', bn: 'স্থানীয় সংবাদ দেখতে আপনার অবস্থান সেট করুন', ta: 'உள்ளூர் செய்திகளைக் காண உங்கள் இடத்தை அமைக்கவும்', te: 'స్థానిక వార్తలను చూడటానికి మీ స్థానాన్ని సెట్ చేయండి' },

  // Tabs
  'tabs.all': { en: 'All', hi: 'सभी', es: 'Todos', fr: 'Tous', de: 'Alle', ar: 'الكل', bn: 'সব', ta: 'அனைத்தும்', te: 'అన్నీ' },
  'tabs.trending': { en: 'Trending', hi: 'ट्रेंडिंग', es: 'Tendencias', fr: 'Tendances', de: 'Trends', ar: 'الرائج', bn: 'ট্রেন্ডিং', ta: 'பிரபலமானவை', te: 'ట్రెండింగ్' },
  'tabs.recent': { en: 'Recent', hi: 'हालिया', es: 'Recientes', fr: 'Récents', de: 'Aktuell', ar: 'الأخيرة', bn: 'সাম্প্রতিক', ta: 'சமீபத்திய', te: 'ఇటీవలి' },
  'tabs.verified': { en: 'Verified', hi: 'वेरिफाइड', es: 'Verificados', fr: 'Vérifiés', de: 'Verifiziert', ar: 'متحقق', bn: 'যাচাইকৃত', ta: 'சரிபார்க்கப்பட்ட', te: 'ధృవీకరించబడింది' },

  // Labels
  'label.trustScore': { en: 'TRUST SCORE', hi: 'ट्रस्ट स्कोर', es: 'PUNTUACIÓN DE CONFIANZA', fr: 'SCORE DE CONFIANCE', de: 'VERTRAUENSBEWERTUNG', ar: 'درجة الثقة', bn: 'বিশ্বাস স্কোর', ta: 'நம்பிக்கை மதிப்பெண்', te: 'విశ్వాస స్కోర్' },
  'label.trustShield': { en: 'Trust Shield', hi: 'ट्रस्ट शील्ड', es: 'Escudo de Confianza', fr: 'Bouclier de Confiance', de: 'Vertrauensschild', ar: 'درع الثقة', bn: 'ট্রাস্ট শিল্ড', ta: 'நம்பிக்கை கவசம்', te: 'విశ్వాస షీల్డ్' },

  // Modal
  'modal.share': { en: 'Share', hi: 'साझा करें', es: 'Compartir', fr: 'Partager', de: 'Teilen', ar: 'مشاركة', bn: 'শেয়ার করুন', ta: 'பகிர்', te: 'షేర్' },
  'modal.analyze': { en: 'Analyze', hi: 'विश्लेषण करें', es: 'Analizar', fr: 'Analyser', de: 'Analysieren', ar: 'تحليل', bn: 'বিশ্লেষণ করুন', ta: 'பகுப்பாய்வு', te: 'విశ్లేషించండి' },

  // Location
  'location.title': { en: 'Set Your Location', hi: 'अपना स्थान सेट करें', es: 'Establece tu Ubicación', fr: 'Définir votre Emplacement', de: 'Standort Festlegen', ar: 'حدد موقعك', bn: 'আপনার অবস্থান সেট করুন', ta: 'உங்கள் இடத்தை அமைக்கவும்', te: 'మీ స్థానాన్ని సెట్ చేయండి' },
  'location.description': { en: 'Get news relevant to your area. Auto-detect or select manually.', hi: 'अपने क्षेत्र से संबंधित समाचार प्राप्त करें। स्वतः पता लगाएं या मैन्युअल रूप से चुनें।', es: 'Obtén noticias relevantes de tu área. Detecta automáticamente o selecciona manualmente.', fr: 'Obtenez des actualités pertinentes pour votre région. Détection automatique ou sélection manuelle.', de: 'Erhalten Sie relevante Nachrichten für Ihre Region. Automatisch erkennen oder manuell auswählen.', ar: 'احصل على الأخبار ذات الصلة بمنطقتك. الكشف التلقائي أو الاختيار اليدوي.', bn: 'আপনার এলাকার প্রাসঙ্গিক সংবাদ পান। স্বয়ংক্রিয়-সনাক্ত করুন বা ম্যানুয়ালি নির্বাচন করুন।', ta: 'உங்கள் பகுதிக்கு பொருத்தமான செய்திகளைப் பெறுங்கள். தானாகக் கண்டறி அல்லது கைமுறையாக தேர்ந்தெடுக்கவும்।', te: 'మీ ప్రాంతానికి సంబంధించిన వార్తలను పొందండి। స్వయంచాలకంగా గుర్తించండి లేదా మాన్యువల్‌గా ఎంచుకోండి।' },
  'location.current': { en: 'Current Location', hi: 'वर्तमान स्थान', es: 'Ubicación Actual', fr: 'Emplacement Actuel', de: 'Aktueller Standort', ar: 'الموقع الحالي', bn: 'বর্তমান অবস্থান', ta: 'தற்போதைய இடம்', te: 'ప్రస్తుత స్థానం' },
  'location.permissionTitle': { en: 'Location Permission Required', hi: 'स্थान अनुमति आवश्यक', es: 'Permiso de Ubicación Requerido', fr: 'Autorisation de Localisation Requise', de: 'Standortberechtigung Erforderlich', ar: 'إذن الموقع مطلوب', bn: 'অবস্থান অনুমতি প্রয়োজন', ta: 'இட அனுமதி தேவை', te: 'స్థాన అనుమతి అవసరం' },
  'location.permissionText': { en: 'We need your permission to detect your location and show relevant local news. Your location is only used on your device and is not shared.', hi: 'आपके स्थान का पता लगाने और संबंधित स्थानीय समाचार दिखाने के लिए हमें आपकी अनुमति चाहिए। आपका स्थान केवल आपके डिवाइस पर उपयोग किया जाता है और साझा नहीं किया जाता है।', es: 'Necesitamos tu permiso para detectar tu ubicación y mostrar noticias locales relevantes. Tu ubicación solo se usa en tu dispositivo y no se comparte.', fr: 'Nous avons besoin de votre autorisation pour détecter votre emplacement et afficher des actualités locales pertinentes. Votre emplacement n\'est utilisé que sur votre appareil et n\'est pas partagé.', de: 'Wir benötigen Ihre Erlaubnis, um Ihren Standort zu erkennen und relevante lokale Nachrichten anzuzeigen. Ihr Standort wird nur auf Ihrem Gerät verwendet und nicht weitergegeben.', ar: 'نحتاج إلى إذنك للكشف عن موقعك وإظهار الأخبار المحلية ذات الصلة. يتم استخدام موقعك فقط على جهازك ولا تتم مشاركته.', bn: 'আপনার অবস্থান সনাক্ত করতে এবং প্রাসঙ্গিক স্থানীয় সংবাদ দেখাতে আমাদের আপনার অনুমতি প্রয়োজন। আপনার অবস্থান শুধুমাত্র আপনার ডিভাইসে ব্যবহার করা হয় এবং শেয়ার করা হয় না।', ta: 'உங்கள் இடத்தைக் கண்டறிய மற்றும் பொருத்தமான உள்ளூர் செய்திகளைக் காட்ட எங்களுக்கு உங்கள் அனுமதி தேவை। உங்கள் இடம் உங்கள் சாதனத்தில் மட்டுமே பயன்படுத்தப்படுகிறது மற்றும் பகிரப்படவில்லை।', te: 'మీ స్థానాన్ని గుర్తించడానికి మరియు సంబంధిత స్థానిక వార్తలను చూపించడానికి మాకు మీ అనుమతి అవసరం। మీ స్థానం మీ పరికరంలో మాత్రమే ఉపయోగించబడుతుంది మరియు భాగస్వామ్యం చేయబడదు।' },
  'location.allow': { en: 'Allow Location Access', hi: 'स्थान एक्सेस की अनुमति दें', es: 'Permitir Acceso a Ubicación', fr: 'Autoriser l\'Accès à l\'Emplacement', de: 'Standortzugriff Erlauben', ar: 'السماح بالوصول إلى الموقع', bn: 'অবস্থান অ্যাক্সেসের অনুমতি দিন', ta: 'இட அணுகலை அனுமதிக்கவும்', te: 'స్థాన యాక్సెస్‌ను అనుమతించండి' },
  'location.deny': { en: 'Not Now', hi: 'अभी नहीं', es: 'Ahora No', fr: 'Pas Maintenant', de: 'Nicht Jetzt', ar: 'ليس الآن', bn: 'এখন নয়', ta: 'இப்போது இல்லை', te: 'ఇప్పుడు కాదు' },
  'location.detecting': { en: 'Detecting...', hi: 'पता लगा रहे हैं...', es: 'Detectando...', fr: 'Détection...', de: 'Erkennen...', ar: 'جاري الكشف...', bn: 'সনাক্ত করা হচ্ছে...', ta: 'கண்டறிகிறது...', te: 'గుర్తిస్తోంది...' },
  'location.autoDetect': { en: 'Auto-Detect My Location', hi: 'मेरे स्थान का स्वतः पता लगाएं', es: 'Detectar Automáticamente Mi Ubicación', fr: 'Détecter Automatiquement Mon Emplacement', de: 'Meinen Standort Automatisch Erkennen', ar: 'الكشف التلقائي عن موقعي', bn: 'আমার অবস্থান স্বয়ংক্রিয়ভাবে সনাক্ত করুন', ta: 'என் இடத்தை தானாகக் கண்டறியவும்', te: 'నా స్థానాన్ని స్వయంచాలకంగా గుర్తించండి' },
  'location.or': { en: 'OR', hi: 'या', es: 'O', fr: 'OU', de: 'ODER', ar: 'أو', bn: 'অথবা', ta: 'அல்லது', te: 'లేదా' },
  'location.selectState': { en: 'Select State', hi: 'राज्य चुनें', es: 'Seleccionar Estado', fr: 'Sélectionner l\'État', de: 'Bundesland Auswählen', ar: 'اختر الولاية', bn: 'রাজ্য নির্বাচন করুন', ta: 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்', te: 'రాష్ట్రాన్ని ఎంచుకోండి' },
  'location.chooseState': { en: 'Choose a state...', hi: 'एक राज्य चुनें...', es: 'Elige un estado...', fr: 'Choisissez un état...', de: 'Wählen Sie ein Bundesland...', ar: 'اختر ولاية...', bn: 'একটি রাজ্য নির্বাচন করুন...', ta: 'ஒரு மாநிலத்தைத் தேர்ந்தெடுக்கவும்...', te: 'ఒక రాష్ట్రాన్ని ఎంచుకోండి...' },
  'location.selectCity': { en: 'Select City/Town', hi: 'शहर/कस्बा चुनें', es: 'Seleccionar Ciudad/Pueblo', fr: 'Sélectionner Ville/Localité', de: 'Stadt/Ort Auswählen', ar: 'اختر المدينة/البلدة', bn: 'শহর/শহর নির্বাচন করুন', ta: 'நகரம்/நகரத்தைத் தேர்ந்தெடுக்கவும்', te: 'నగరం/పట్టణం ఎంచుకోండి' },
  'location.chooseCity': { en: 'Choose a city...', hi: 'एक शहर चुनें...', es: 'Elige una ciudad...', fr: 'Choisissez une ville...', de: 'Wählen Sie eine Stadt...', ar: 'اختر مدينة...', bn: 'একটি শহর নির্বাচন করুন...', ta: 'ஒரு நகரத்தைத் தேர்ந்தெடுக்கவும்...', te: 'ఒక నగరాన్ని ఎంచుకోండి...' },
  'location.optional': { en: 'optional', hi: 'वैकल्पिक', es: 'opcional', fr: 'facultatif', de: 'optional', ar: 'اختياري', bn: 'ঐচ্ছিক', ta: 'விரும்பினால்', te: 'ఐచ్ఛికం' },
  'location.confirm': { en: 'Confirm Location', hi: 'स्थान की पुष्टि करें', es: 'Confirmar Ubicación', fr: 'Confirmer l\'Emplacement', de: 'Standort Bestätigen', ar: 'تأكيد الموقع', bn: 'অবস্থান নিশ্চিত করুন', ta: 'இடத்தை உறுதிப்படுத்தவும்', te: 'స్థానాన్ని నిర్ధారించండి' },
  'location.showingFor': { en: 'Showing news for', hi: 'समाचार दिखा रहे हैं', es: 'Mostrando noticias de', fr: 'Affichage des actualités pour', de: 'Zeige Nachrichten für', ar: 'عرض الأخبار لـ', bn: 'সংবাদ দেখানো হচ্ছে', ta: 'செய்திகள் காட்டப்படுகின்றன', te: 'వార్తలు చూపిస్తోంది' },
  'location.set': { en: 'Set Location', hi: 'स्थान सेट करें', es: 'Establecer Ubicación', fr: 'Définir l\'Emplacement', de: 'Standort Festlegen', ar: 'تعيين الموقع', bn: 'অবস্থান সেট করুন', ta: 'இடத்தை அமைக்கவும்', te: 'స్థానాన్ని సెట్ చేయండి' },
  'location.change': { en: 'Change Location', hi: 'स्थान बदलें', es: 'Cambiar Ubicación', fr: 'Changer l\'Emplacement', de: 'Standort Ändern', ar: 'تغيير الموقع', bn: 'অবস্থান পরিবর্তন করুন', ta: 'இடத்தை மாற்றவும்', te: 'స్థానాన్ని మార్చండి' },

  // Authentication
  'auth.login': { en: 'Login', hi: 'लॉगिन', es: 'Iniciar Sesión', fr: 'Connexion', de: 'Anmelden', ar: 'تسجيل الدخول', bn: 'লগইন', ta: 'உள்நுழைவு', te: 'లాగిన్' },
  'auth.signup': { en: 'Sign Up', hi: 'साइन अप', es: 'Registrarse', fr: 'S\'Inscrire', de: 'Registrieren', ar: 'التسجيل', bn: 'সাইন আপ', ta: 'பதிவு செய்க', te: 'సైన్ అప్' },
  'auth.logout': { en: 'Logout', hi: 'लॉगआउट', es: 'Cerrar Sesión', fr: 'Déconnexion', de: 'Abmelden', ar: 'تسجيل الخروج', bn: 'লগআউট', ta: 'வெளியேறு', te: 'లాగౌట్' },
  'auth.loginSubtitle': { en: 'Access personalized news from your area', hi: 'अपने क्षेत्र से व्यक्तिगत समाचार एक्सेस करें', es: 'Accede a noticias personalizadas de tu área', fr: 'Accédez aux actualités personnalisées de votre région', de: 'Zugriff auf personalisierte Nachrichten aus Ihrer Region', ar: 'الوصول إلى الأخبار المخصصة من منطقتك', bn: 'আপনার এলাকা থেকে ব্যক্তিগত সংবাদ অ্যাক্সেস করুন', ta: 'உங்கள் பகுதியிலிருந்து தனிப்பயனாக்கப்பட்ட செய்திகளை அணுகவும்', te: 'మీ ప్రాంతం నుండి వ్యక్తిగతీకరించిన వార్తలను యాక్సెస్ చేయండి' },
  'auth.signupSubtitle': { en: 'Create account to get location-based news', hi: 'स्थान-आधारित समाचार के लिए खाता बनाएं', es: 'Crea una cuenta para obtener noticias locales', fr: 'Créez un compte pour obtenir des actualités locales', de: 'Konto erstellen, um standortbasierte Nachrichten zu erhalten', ar: 'إنشاء حساب للحصول على الأخبار المحلية', bn: 'স্থান-ভিত্তিক সংবাদ পেতে অ্যাকাউন্ট তৈরি করুন', ta: 'இடம் சார்ந்த செய்திகளைப் பெற கணக்கை உருவாக்கவும்', te: 'స్థాన-ఆధారిత వార్తలను పొందడానికి ఖాతాను సృష్టించండి' },
  'auth.name': { en: 'Full Name', hi: 'पूरा नाम', es: 'Nombre Completo', fr: 'Nom Complet', de: 'Vollständiger Name', ar: 'الاسم الكامل', bn: 'পুরো নাম', ta: 'முழு பெயர்', te: 'పూర్తి పేరు' },
  'auth.namePlaceholder': { en: 'Enter your name', hi: 'अपना नाम दर्ज करें', es: 'Ingresa tu nombre', fr: 'Entrez votre nom', de: 'Geben Sie Ihren Namen ein', ar: 'أدخل اسمك', bn: 'আপনার নাম লিখুন', ta: 'உங்கள் பெயரை உள்ளிடவும்', te: 'మీ పేరు నమోదు చేయండి' },
  'auth.email': { en: 'Email Address', hi: 'ईमेल पता', es: 'Correo Electrónico', fr: 'Adresse E-mail', de: 'E-Mail-Adresse', ar: 'عنوان البريد الإلكتروني', bn: 'ইমেইল ঠিকানা', ta: 'மின்னஞ்சல் முகவரி', te: 'ఇమెయిల్ చిరునామా' },
  'auth.emailPlaceholder': { en: 'your@email.com', hi: 'your@email.com', es: 'tu@email.com', fr: 'votre@email.com', de: 'ihre@email.com', ar: 'your@email.com', bn: 'your@email.com', ta: 'your@email.com', te: 'your@email.com' },
  'auth.password': { en: 'Password', hi: 'पासवर्ड', es: 'Contraseña', fr: 'Mot de Passe', de: 'Passwort', ar: 'كلمة المرور', bn: 'পাসওয়ার্ড', ta: 'கடவுச்சொல்', te: 'పాస్‌వర్డ్' },
  'auth.passwordPlaceholder': { en: 'Minimum 6 characters', hi: 'कम से कम 6 अक्षर', es: 'Mínimo 6 caracteres', fr: 'Minimum 6 caractères', de: 'Mindestens 6 Zeichen', ar: 'على الأقل 6 أحرف', bn: 'কমপক্ষে ৬টি অক্ষর', ta: 'குறைந்தபட்சம் 6 எழுத்துக்கள்', te: 'కనీసం 6 అక్షరాలు' },
  'auth.passwordHint': { en: 'At least 6 characters required', hi: 'कम से कम 6 अक्षर आवश्यक', es: 'Se requieren al menos 6 caracteres', fr: 'Au moins 6 caractères requis', de: 'Mindestens 6 Zeichen erforderlich', ar: 'مطلوب 6 أحرف على الأقل', bn: 'কমপক্ষে ৬টি অক্ষর প্রয়োজন', ta: 'குறைந்தபட்சம் 6 எழுத்துக்கள் தேவை', te: 'కనీసం 6 అక్షరాలు అవసరం' },
  'auth.loading': { en: 'Please wait...', hi: 'कृपया प्रतीक्षा करें...', es: 'Por favor espera...', fr: 'Veuillez patienter...', de: 'Bitte warten...', ar: 'الرجاء الانتظار...', bn: 'অপেক্ষা করুন...', ta: 'காத்திருக்கவும்...', te: 'దయచేసి వేచి ఉండండి...' },
  'auth.loginButton': { en: 'Login to Account', hi: 'खाते में लॉगिन करें', es: 'Iniciar Sesión en la Cuenta', fr: 'Se Connecter au Compte', de: 'Bei Konto Anmelden', ar: 'تسجيل الدخول إلى الحساب', bn: 'অ্যাকাউন্টে লগইন করুন', ta: 'கணக்கில் உள்நுழைக', te: 'ఖాతాలోకి లాగిన్ అవ్వండి' },
  'auth.signupButton': { en: 'Create Account', hi: 'खाता बनाएं', es: 'Crear Cuenta', fr: 'Créer un Compte', de: 'Konto Erstellen', ar: 'إنشاء حساب', bn: 'অ্যাকাউন্ট তৈরি করুন', ta: 'கணக்கை உருவாக்கவும்', te: 'ఖాతా సృష్టించండి' },
  'auth.noAccount': { en: "Don't have an account? Sign up", hi: 'खाता नहीं है? साइन अप करें', es: '¿No tienes cuenta? Regístrate', fr: 'Vous n\'avez pas de compte ? Inscrivez-vous', de: 'Noch kein Konto? Registrieren', ar: 'ليس لديك حساب؟ سجل', bn: 'অ্যাকাউন্ট নেই? সাইন আপ করুন', ta: 'கணக்கு இல்லையா? பதிவு செய்யவும்', te: 'ఖాతా లేదా? సైన్ అప్ చేయండి' },
  'auth.haveAccount': { en: 'Already have an account? Login', hi: 'पहले से खाता है? लॉगिन करें', es: '¿Ya tienes cuenta? Inicia sesión', fr: 'Vous avez déjà un compte ? Connectez-vous', de: 'Haben Sie bereits ein Konto? Anmelden', ar: 'هل لديك حساب؟ تسجيل الدخول', bn: 'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন', ta: 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக', te: 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి' },
  'auth.demoNote': { en: 'Demo: Data stored locally. Max 10 users.', hi: 'डेमो: डेटा स्थानीय रूप से संग्रहीत। अधिकतम 10 उपयोगकर्ता।', es: 'Demo: Datos almacenados localmente. Máx. 10 usuarios.', fr: 'Démo: Données stockées localement. Max 10 utilisateurs.', de: 'Demo: Daten lokal gespeichert. Max. 10 Benutzer.', ar: 'تجريبي: البيانات محفوظة محلياً. حد أقصى 10 مستخدمين.', bn: 'ডেমো: ডেটা স্থানীয়ভাবে সংরক্ষিত। সর্বোচ্চ ১০ ব্যবহারকারী।', ta: 'டெமோ: தரவு உள்ளூரில் சேமிக்கப்பட்டுள்ளது। அதிகபட்சம் 10 பயனர்கள்।', te: 'డెమో: డేటా స్థానికంగా నిల్వ చేయబడింది। గరిష్టంగా 10 వినియోగదారులు।' },
  'auth.loggedInAs': { en: 'Logged in as', hi: 'के रूप में लॉग इन', es: 'Conectado como', fr: 'Connecté en tant que', de: 'Angemeldet als', ar: 'مسجل الدخول كـ', bn: 'হিসাবে লগইন করা হয়েছে', ta: 'இவராக உள்நுழைந்துள்ளீர்கள்', te: 'గా లాగిన్ అయ్యారు' },

  // Submission
  'submission.title': { en: 'Agentic AI: Crisis Misinformation Watch', hi: 'एजेंटिक एआई: संकट गलत सूचना निगरानी', es: 'IA Agentiva: Vigilancia de Desinformación en Crisis', fr: 'IA Agentique: Surveillance de la Désinformation en Crise', de: 'Agentische KI: Krisenüberwachung von Fehlinformationen', ar: 'الذكاء الاصطناعي الوكيل: مراقبة المعلومات المضللة في الأزمات', bn: 'এজেন্টিক এআই: সংকট ভুল তথ্য নজরদারি', ta: 'ஏஜென்டிக் AI: நெருக்கடி தவறான தகவல் கண்காணிப்பு', te: 'ఏజెంటిక్ AI: సంక్షోభ తప్పుడు సమాచార పర్యవేక్షణ' },
  'submission.tagline': { en: 'An AI agent that continuously scans multi-channel content streams, detects emerging misinformation during global or local crises, verifies claims via cross-references, and produces accessible, contextual explanations tailored to diverse audiences.', hi: 'एक एआई एजेंट जो बहु-चैनल कंटेंट स्ट्रीम्स को निरंतर स्कैन करता है, संकटों के दौरान उभरती गलत सूचनाओं का पता लगाता है, क्रॉस-रेफरेंस के माध्यम से दावों की पुष्टि करता है, और विविध दर्शकों के लिए सुलभ, संदर्भित स्पष्टीकरण तैयार करता है।', es: 'Un agente de IA que escanea continuamente flujos de contenido multicanal, detecta desinformación emergente durante crisis globales o locales, verifica afirmaciones mediante referencias cruzadas y produce explicaciones contextuales accesibles adaptadas a audiencias diversas.', fr: 'Un agent d\'IA qui analyse en continu les flux de contenu multicanaux, détecte la désinformation émergente lors de crises mondiales ou locales, vérifie les affirmations par recoupement et produit des explications contextuelles accessibles adaptées à des publics divers.', de: 'Ein KI-Agent, der kontinuierlich Mehrkanalinhaltsströme scannt, aufkommende Fehlinformationen während globaler oder lokaler Krisen erkennt, Behauptungen durch Querverweise überprüft und zugängliche, kontextuelle Erklärungen für verschiedene Zielgruppen erstellt.', ar: 'وكيل ذكاء اصطناعي يفحص باستمرار تدفقات المحتوى متعددة القنوات، ويكتشف المعلومات المضللة الناشئة خلال الأزمات العالمية أو المحلية، ويتحقق من المزاعم عبر المراجع المتقاطعة، وينتج تفسيرات سياقية يسهل الوصول إليها مصممة لجماهير متنوعة.', bn: 'একটি এআই এজেন্ট যা ক্রমাগত মাল্টি-চ্যানেল কন্টেন্ট স্ট্রিম স্ক্যান করে, বৈশ্বিক বা স্থানীয় সংকটের সময় উদীয়মান ভুল তথ্য সনাক্ত করে, ক্রস-রেফারেন্সের মাধ্যমে দাবি যাচাই করে এবং বিভিন্ন দর্শকদের জন্য উপযুক্ত অ্যাক্সেসযোগ্য, প্রাসঙ্গিক ব্যাখ্যা তৈরি করে।', ta: 'ஒரு AI முகவர் தொடர்ந்து பல-சேனல் உள்ளடக்க ஓட்டங்களை ஸ்கேன் செய்கிறது, உலகளாவிய அல்லது உள்ளூர் நெருக்கடிகளின் போது வெளிப்படும் தவறான தகவலைக் கண்டறிகிறது, குறுக்கு-குறிப்புகள் வழியாக கூற்றுகளை சரிபார்க்கிறது, மற்றும் பல்வேறு பார்வையாளர்களுக்கு ஏற்ற அணுகக்கூடிய, சூழல் சார்ந்த விளக்கங்களை உருவாக்குகிறது।', te: 'ఒక AI ఏజెంట్ నిరంతరం బహుళ-ఛానల్ కంటెంట్ స్ట్రీమ్‌లను స్కాన్ చేస్తుంది, ప్రపంచ లేదా స్థానిక సంక్షోభాల సమయంలో ఉద్భవిస్తున్న తప్పుడు సమాచారాన్ని గుర్తిస్తుంది, క్రాస్-రిఫరెన్స్‌ల ద్వారా దావాలను ధృవీకరిస్తుంది మరియు విభిన్న ప్రేక్షకులకు అనుగుణంగా అందుబాటులో ఉండే, సందర్భోచిత వివరణలను ఉత్పత్తి చేస్తుంది।' },

  // Login Options Page
  'login.options.title': { en: 'Choose how you want to continue', hi: 'जारी रखने के लिए विकल्प चुनें', es: 'Elige cómo quieres continuar', fr: 'Choisissez comment continuer', de: 'Wählen Sie, wie Sie fortfahren möchten', ar: 'اختر كيفية المتابعة', bn: 'আপনি কীভাবে চালিয়ে যেতে চান তা নির্বাচন করুন', ta: 'எவ்வாறு தொடர விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்', te: 'మీరు ఎలా కొనసాగాలనుకుంటున్నారో ఎంచుకోండి' },
  'login.options.subtitle': { en: 'Pick a role to sign in', hi: 'साइन इन के लिए भूमिका चुनें', es: 'Selecciona un rol para iniciar sesión', fr: 'Choisissez un rôle pour vous connecter', de: 'Wählen Sie eine Rolle zum Anmelden', ar: 'اختر دورًا لتسجّل الدخول', bn: 'সাইন ইন করার জন্য একটি ভূমিকা নির্বাচন করুন', ta: 'உள்நுழைய ஒரு பாத்திரத்தைத் தேர்ந்தெடுக்கவும்', te: 'సైన్ ఇన్ కోసం పాత్రను ఎంచుకోండి' },
  'login.role.user': { en: 'User', hi: 'उपयोगकर्ता', es: 'Usuario', fr: 'Utilisateur', de: 'Benutzer', ar: 'مستخدم', bn: 'ব্যবহারকারী', ta: 'பயனர்', te: 'వినియోగదారు' },
  'login.role.contributor': { en: 'Contributor', hi: 'योगदानकर्ता', es: 'Colaborador', fr: 'Contributeur', de: 'Mitwirkender', ar: 'مساهم', bn: 'অবদানকারী', ta: 'பங்களிப்பாளர்', te: 'కాంట్రిబ్యూటర్' },
  'login.role.admin': { en: 'Admin', hi: 'प्रशासक', es: 'Administrador', fr: 'Administrateur', de: 'Admin', ar: 'مشرف', bn: 'অ্যাডমিন', ta: 'நிர்வாகி', te: 'అడ్మిన్' },
  'login.continue': { en: 'Continue', hi: 'जारी रखें', es: 'Continuar', fr: 'Continuer', de: 'Fortfahren', ar: 'متابعة', bn: 'চালিয়ে যান', ta: 'தொடரவும்', te: 'కొనసాగించండి' },
  'login.back': { en: 'Back', hi: 'वापस', es: 'Atrás', fr: 'Retour', de: 'Zurück', ar: 'رجوع', bn: 'পিছনে', ta: 'பின்செல்', te: 'వెనక్కి' },
};

// Transform base translations into language-specific objects
export const translations = {};
Object.keys(baseTranslations).forEach(key => {
  Object.keys(baseTranslations[key]).forEach(lang => {
    if (!translations[lang]) translations[lang] = {};
    translations[lang][key] = baseTranslations[key][lang];
  });
});
