name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
      
      - name: Build Backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build
      
      - name: Deploy
        run: |
          echo "Deployment step - configure for your platform"
          echo "Examples: AWS, Heroku, DigitalOcean, Vercel, Netlify"
